apiVersion: v1
kind: Service
metadata:
  name: sleep-quality-prediction
spec:
  type: NodePort
  selector:
    app: sleep-quality-prediction
  ports:
  - protocol: TCP
    port: 9696
    targetPort: 9696
    nodePort: 30080